plugins {
    id 'fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

evaluationDependsOn(":neoforge")

version = project.mod_version
group = project.mod_group

base {
    archivesName = project.mod_id + "-fabric"
}

repositories {

}

sourceSets {
    main {
        java {
            srcDir project(':common').file('src/main/java')
        }
        resources {
            srcDir project(':common').file('src/main/resources')
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
}

processResources {
    def version = project.version
    inputs.property "version", version

    filesMatching("fabric.mod.json") {
        expand "version": version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.mod_id}" }
    }
}

apply plugin: "me.modmuss50.mod-publish-plugin"

publishMods {
    displayName = "FastMapCodec ${project.version}"
    file = tasks.named('remapJar').flatMap { it.archiveFile }
    changelog = providers.environmentVariable("CHANGELOG").orElse("See commits for changes.")
    type = STABLE
    modLoaders.add("fabric")
    dryRun = !providers.environmentVariable("CI").isPresent()

    github {
        repository = "nekotxs/fastmapcodec"
        accessToken = providers.environmentVariable("GITHUB_TOKEN")
        commitish = "main"

        parent(project(":neoforge").tasks.named("publishGithub"))
    }
    modrinth {
        projectId = "CN7axcWy"
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        minecraftVersionRange {
            start = "1.21"
            end = "26.2"
        }
    }
    curseforge {
        projectId = "1637069"
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        minecraftVersionRange {
            start = "1.21"
            end = "26.2"
        }
        javaVersions.add(JavaVersion.VERSION_21)
        client = true
        server = true
    }
}
