plugins {
    id "me.modmuss50.mod-publish-plugin" version "0.8.+" apply false
}

subprojects {
    apply plugin: "java"

    java {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
    }

    group = mod_group
    version = mod_version

    repositories {
        mavenCentral()
    }
}
