modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/nekotxs/fastmapcodec/issues"

[[mods]]
modId = "fastmapcodec"
version = "${file.jarVersion}"
authors="nekotxs"
logoFile="icon.png"
logoBlur=false
displayName = "FastMapCodec"
displayURL="https://github.com/nekotxs/fastmapcodec"
description = '''
Fixes O(n^2) in BaseMapCodec.decode (TPS freezes on player join mainly)
'''

[[mixins]]
config = "fastmapcodec.mixins.json"

[[dependencies.fastmapcodec]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.fastmapcodec]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21,)"
    ordering = "NONE"
    side = "BOTH"
