plugins {
    id "net.neoforged.moddev" version "2.0.+"
}

base {
    archivesName = mod_id + "-neoforge"
}

sourceSets {
    mod
}

sourceSets.mod.java.srcDir project(":common").sourceSets.main.java.srcDirs
sourceSets.mod.resources.srcDir project(":common").sourceSets.main.resources.srcDirs

neoForge {
    version = neoforge_version

    addModdingDependenciesTo sourceSets.mod

    mods {
        fastmapcodec {
            sourceSet sourceSets.mod
        }
    }
}

dependencies {
    compileOnly "cpw.mods:modlauncher:11.0.5"
    compileOnly "cpw.mods:securejarhandler:3.0.8" // TODO: свериться с фактической версией
}

tasks.register('modJar', Jar) {
    archiveFileName = "fastmapcodec-${project.mod_version}-mod.jar"
    from sourceSets.mod.output
    manifest {
        attributes(["Implementation-Version": project.mod_version])
    }
}

tasks.named('jar', Jar) {
    dependsOn tasks.named('modJar')
    from(sourceSets.mod.resources.srcDirs) {
        include 'META-INF/neoforge.mods.toml'
        include 'icon.png'
    }
    into('META-INF/jarjar') {
        from tasks.named('modJar')
    }
    manifest {
        attributes(["Implementation-Version": project.mod_version])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

apply plugin: "me.modmuss50.mod-publish-plugin"

publishMods {
    displayName = "FastMapCodec NeoForge ${project.mod_version}"
    file = tasks.named('jar').flatMap { it.archiveFile }
    changelog = providers.environmentVariable("CHANGELOG").orElse("See commits for changes.")
    type = STABLE
    modLoaders.add("neoforge")
    dryRun = !providers.environmentVariable("CI").isPresent()

    github {
        repository = "nekotxs/fastmapcodec"
        accessToken = providers.environmentVariable("GITHUB_TOKEN")
        commitish = "main"
    }

    modrinth {
        projectId = "CN7axcWy"
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        minecraftVersionRange {
            start = "1.21"
            end = "26.2"
        }
    }

    curseforge {
        projectId = "1637069" // тот же ID проекта, что у neoforge-версии
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        minecraftVersionRange {
            start = "1.21"
            end = "26.2"
        }
        client = true
        server = true
    }
}
